// Auto-generated by scripts/upload-valentine-poses.mjs.
// Maps the original screenshot filename (also the experiencedPositionIds
// key in Mongo) to its Vercel Blob URL. Do not hand-edit — re-run the
// upload script if the catalogue changes.

export interface ValentinePoseEntry {
  filename: string;
  url: string;
}

export const VALENTINE_POSES: readonly ValentinePoseEntry[] = [
  {
    "filename": "Screenshot 2026-02-10 at 22.27.16.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-22-27-16-gEXv7dmSzmgBIH8cbeIj1915IzKDDp.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 22.28.13.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-22-28-13-S3Affao8pxi16w9Yq0H5CX6AE4fzTI.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 22.28.25.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-22-28-25-q7MxdnoG2h4UofLDeueYzQwC19d9GO.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.08.38.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-08-38-zYRsGsBVK1uvvrN6oPhQHPkql8YlW3.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.08.47.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-08-47-3eCxSj8vgoD9quUpslKocIXPPScckv.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.08.53.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-08-53-a1liOVY5htec4vEV14V1DwcVcg4RLA.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.09.06.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-09-06-1iQMlaozzwGgRnUVoNdPbT2wrDOiTX.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.09.16.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-09-16-j7wxPvQgQhd42S8ZCcnVAGxPWfmYSW.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.09.26.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-09-26-5izFxe1i0sTlpG3bXQKf9j5AjWQ21k.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.09.32.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-09-32-9cyvkLcOEYjIfb5BNdr9wVdUjIvrQV.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.09.40.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-09-40-SeaLjl0KRNCBDfhuwx3GI9eU9NF8ON.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.09.46.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-09-46-SeaNouGSXeOxGzAyc0pSWF2qB7vaDr.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.09.55.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-09-55-Pp5cdr0a4ZmkANM9vuVXr9CKLV293O.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.10.02.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-10-02-O1NGmgHp4dypJ2ibq7V8nAgJDiZebY.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.10.07.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-10-07-FY2u9IeEwDqP2IXknZaoG49OjXqXw3.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.10.16.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-10-16-PYoV8wJ5iR3j45J17ftLzjdnXXUl6S.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.13.30.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-13-30-7JQIi4N1KP7RpMYEmtN4DyfWNsfCr5.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.13.38.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-13-38-o1ik3f1U5Pi05LoV76VyIbWEyHjEmN.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.13.50.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-13-50-evHp7pqVeyXGtsACPdjjK2riZtNKCn.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.13.56.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-13-56-dho6R9YICf1b8HDCvA04KKJ0GgE08P.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.14.05.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-14-05-8pCxiuO53pcFoVsb0hrgDk1FvbTh7A.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.14.11.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-14-11-62zeh8fXLnshEzLF4gWupTdmtiujtV.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.14.18.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-14-18-S5L4puvEsOx90G4eT7EqcexzIfzU3J.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.14.25.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-14-25-00URkYNYL6b7FiYz43YmB5SdT9fU0F.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.14.33.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-14-33-eJwE3vAjOae9q1by4BS48nw0KkgZKb.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.14.39.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-14-39-amNtgQAz8Wqy0TOySwGBMCxppoSgDf.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.14.45.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-14-45-wTmXmBWdbI8YlpO591rXBfqxOzRjHa.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.14.55.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-14-55-MUlEhXjaXxXva60WGjE6cFFKHvksXP.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.15.00.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-00-KwLPo4kPF2gAg3cbIIF57xGpRvGouY.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.15.14.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-14-Vubrozumrp0v1nXvqdu6MUjkYtJEb5.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.15.21.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-21-KqbmKyOwGGtvPNSu2Kxfc7WvypVFQ5.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.15.26.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-26-82kAhGwn5yBh9H1vrz3HMGV7nVJQpk.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.15.33.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-33-0JNXbyE9ZEGpmlPb0nYC8UXqkESXK2.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.15.37.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-37-y9wBXfVjiLcmX8xSjTxgbbMaq9n9jm.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.15.45.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-45-M7h0gv7zuZwygWGIKIN9ypwzSBkgRm.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.15.53.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-53-tF2iVBZtiv7dNURcKFBZ09qRe8Yirt.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.15.57.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-57-PIm0JvXVTg7UytoDQ0vbfwGCFW8FmU.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.16.04.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-04-oUuWBJDlvVzEkUye2pHKOtUpNnWzsn.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.16.12.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-12-DNplnALkT04GKpiFzrgiG8q7Vjfoi9.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.16.19.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-19-oZok4i4aitY0m7vi3kcU8lQLJgkLLT.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.16.24.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-24-HPRZ9sO3hq5EERoVNABSDWTIwTEIC6.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.16.30.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-30-hxmfaFwRpyGU53wOvXkiptrIvcauJ5.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.16.38.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-38-9IQka1I2ujeU2HJb93HLEnIxM3KqTU.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.16.43.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-43-7zQYDaUV36mqkgEOYt86evSCuqqyGU.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.16.47.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-47-bZaZzCsHd8yNbKqp80xF5p5ZZgGNN6.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.16.52.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-52-CBu4uFNOLumcsNm6ez7h05VZ8yIBnS.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.16.57.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-57-yks4UGzIqB2PC2DtA0rRhVf148ADK7.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.17.04.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-17-04-Rvokr4JGvCirm0fUWHDo3lkj0qq8iG.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.17.14.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-17-14-0mN2dO0OqYHWEvkudb8b3Kyf3irGVG.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.17.21.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-17-21-MTeSUyXwQlJ8I9j5Lo4pmFdM3XqG9B.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.17.26.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-17-26-jHwYPeFh8H1h0zY8df1aN44EVmu4mQ.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.17.30.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-17-30-QuwzJJsHayuyG0YQc5COjUD4uD4v4T.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.17.40.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-17-40-YGhf42S2qdVszFoD39gUJ3wNZ2EqPI.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.17.45.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-17-45-32ZJBAIa4kDDNM4IJpyevESuAqCXpW.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.17.59.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-17-59-xzruegsMkJCro8z4nckcJ0Em15yg4m.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.18.07.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-18-07-pwA7yvnBjTA1jO0tRWMfg9w0SD7eky.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.18.15.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-18-15-dfjQCeNrIXHqR55TiP2UTErLj74tSN.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.18.19.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-18-19-D57VAO9eqTfYPDNmogSUm7RUo69X7o.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.18.24.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-18-24-20aFP9CDYEqeDdriW5X3tlQW1PJ5zP.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.18.30.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-18-30-OOkqlTHPnaHvvpDG9J8ugrsansl3SJ.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.18.59.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-18-59-o1MQzcax0wAd8LbfUwpBbEKcWYdKef.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.19.08.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-19-08-sNCMFBBB8qEAwOwctboo1rjwVaPz0c.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.19.15.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-19-15-YJjBsFfZLG46PRSGtnp8XUWNVUmqPa.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.19.31.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-19-31-gF93kEL2I2XFzw9VqoM7HxLAGco5nZ.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.19.43.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-19-43-EhxQPwBV4BzUHp7onJRYLFLGcbfMf0.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.19.48.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-19-48-KNUJbayjC60TA7Nd06GPzXiwiSHmU8.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.20.06.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-20-06-CgvqEgcNEI2HdoRRjG0cI7HzsvM0QP.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.20.17.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-20-17-P8RVIpDjQ7Ml39VH6poTJDJsQdsl1M.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.20.35.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-20-35-HbVpi1heY9keqiHEN3Ntvu5gJ47eDK.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.20.41.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-20-41-AwSY7zEdAfwz8EqIr7NK7XgniAoJzS.webp"
  },
  {
    "filename": "Screenshot 2026-02-15 at 13.28.37.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-15-at-13-28-37-Dz1qBpkEDMq9O6QjHsjlvoHs0BCQ6V.webp"
  },
  {
    "filename": "Screenshot 2026-02-16 at 11.17.47.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-16-at-11-17-47-aldPT51SaQgvY914705T3uf8DmxbnK.webp"
  },
  {
    "filename": "Screenshot 2026-02-16 at 11.22.35.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-16-at-11-22-35-KrEbF9IQ09M9JoZK0GoLhRyEC0M4LH.webp"
  },
  {
    "filename": "Screenshot 2026-02-17 at 14.08.39.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-17-at-14-08-39-pg7a37db2P1nLR8xd6fTkmyIuSorSq.webp"
  },
  {
    "filename": "Screenshot 2026-02-17 at 14.09.31.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-17-at-14-09-31-4qupW38EyCidQbNSWkSiQqbT6Vtkk9.webp"
  },
  {
    "filename": "Screenshot 2026-02-18 at 16.36.10.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-18-at-16-36-10-rEyWGRag12NlybTDIwazzh8tkk6TB6.webp"
  },
  {
    "filename": "Screenshot 2026-02-19 at 11.09.01.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-19-at-11-09-01-MkB2pg8flqehKV9eDklWYg2aAzO4pc.webp"
  },
  {
    "filename": "Screenshot 2026-02-20 at 18.17.08.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-20-at-18-17-08-0ismzM48tjYBcKLMh3fQtYxQi29rsR.webp"
  },
  {
    "filename": "Screenshot 2026-02-20 at 19.33.24.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-20-at-19-33-24-TZ3FVUYQg8L7w4ofBuyLMdMqam3NPl.webp"
  },
  {
    "filename": "Screenshot 2026-02-20 at 19.33.45.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-20-at-19-33-45-QMwB60ucpCS6cSK5gXhz5OLRVKNL9T.webp"
  }
] as const;

export const VALENTINE_POSES_BY_FILENAME: Readonly<Record<string, string>> =
  Object.fromEntries(VALENTINE_POSES.map((p) => [p.filename, p.url]));
