// Auto-generated by scripts/upload-valentine-poses.mjs +
// scripts/upload-valentine-thumbs.mjs. Maps the original screenshot
// filename (also the experiencedPositionIds key in Mongo) to its Vercel
// Blob URLs — `url` is the 900 px modal-size image, `thumbUrl` is the
// 400 px grid thumbnail. Do not hand-edit — re-run the upload scripts if
// the catalogue changes.

export interface ValentinePoseEntry {
  filename: string;
  url: string;
  thumbUrl: string;
}

export const VALENTINE_POSES: readonly ValentinePoseEntry[] = [
  {
    "filename": "Screenshot 2026-02-10 at 22.27.16.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-22-27-16-gEXv7dmSzmgBIH8cbeIj1915IzKDDp.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-22-27-16-thumb-MfXwxPnF2AFILyLf8a2ANI0rqP1pCN.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 22.28.13.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-22-28-13-S3Affao8pxi16w9Yq0H5CX6AE4fzTI.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-22-28-13-thumb-UKpB4TGFgvLce0j6D9oMk9fh5UDe2Z.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 22.28.25.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-22-28-25-q7MxdnoG2h4UofLDeueYzQwC19d9GO.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-22-28-25-thumb-qNf2Dz8ruCW55sjVQzQOBMCLIlTDd5.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.08.38.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-08-38-zYRsGsBVK1uvvrN6oPhQHPkql8YlW3.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-08-38-thumb-4QDKEO5JiZg1xWDis0P37Z2BMoyx6x.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.08.47.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-08-47-3eCxSj8vgoD9quUpslKocIXPPScckv.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-08-47-thumb-DX8nqsMU1YWzWBhkngzqEwlQ7mvMkE.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.08.53.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-08-53-a1liOVY5htec4vEV14V1DwcVcg4RLA.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-08-53-thumb-gZkq2SF8ikfTAvsb0vrYA5vk8KC9Ye.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.09.06.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-09-06-1iQMlaozzwGgRnUVoNdPbT2wrDOiTX.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-09-06-thumb-6WRh07HNQpe4sTGCSypLsABwMe4Ahx.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.09.16.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-09-16-j7wxPvQgQhd42S8ZCcnVAGxPWfmYSW.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-09-16-thumb-ITclkMoBKkiq8jslY5xrNuBoKIY8Bd.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.09.26.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-09-26-5izFxe1i0sTlpG3bXQKf9j5AjWQ21k.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-09-26-thumb-FAoR7GiiH9jeikaV7FlD4ueI7KTPEO.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.09.32.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-09-32-9cyvkLcOEYjIfb5BNdr9wVdUjIvrQV.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-09-32-thumb-hh1PPBjqEABlQXQliG4sbc5kcTz58N.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.09.40.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-09-40-SeaLjl0KRNCBDfhuwx3GI9eU9NF8ON.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-09-40-thumb-SQzRiVScWgXGn3cKwIYQAs4ljB9v23.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.09.46.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-09-46-SeaNouGSXeOxGzAyc0pSWF2qB7vaDr.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-09-46-thumb-jy2VCPxMqkaA3Vz4UUhb8hU4ixK8fO.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.09.55.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-09-55-Pp5cdr0a4ZmkANM9vuVXr9CKLV293O.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-09-55-thumb-srRo8rZ6zezxBvOW0Q6S0dJDX3yow2.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.10.02.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-10-02-O1NGmgHp4dypJ2ibq7V8nAgJDiZebY.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-10-02-thumb-pxJeWn0X95oFnKP7fHhQt5hP3FBuxI.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.10.07.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-10-07-FY2u9IeEwDqP2IXknZaoG49OjXqXw3.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-10-07-thumb-omYGyRDXieY9GcdkhqMdOHpFDoYMe8.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.10.16.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-10-16-PYoV8wJ5iR3j45J17ftLzjdnXXUl6S.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-10-16-thumb-T7Qp5mrxjXBxU2MuVlnzYFTUcQY48k.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.13.30.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-13-30-7JQIi4N1KP7RpMYEmtN4DyfWNsfCr5.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-13-30-thumb-eudTfPbhePnjuSZqV3xq8F5P5L8nMP.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.13.38.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-13-38-o1ik3f1U5Pi05LoV76VyIbWEyHjEmN.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-13-38-thumb-Dwr3jAFDdrk3rsZnaQ7jbRn31qNiwJ.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.13.50.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-13-50-evHp7pqVeyXGtsACPdjjK2riZtNKCn.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-13-50-thumb-YfRL3gZ4A01CxF9rsEqxjFejQjPkBp.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.13.56.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-13-56-dho6R9YICf1b8HDCvA04KKJ0GgE08P.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-13-56-thumb-jEroJHaYKcI9e8H7dBYEGoRrrO10OH.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.14.05.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-14-05-8pCxiuO53pcFoVsb0hrgDk1FvbTh7A.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-14-05-thumb-gF66jopeOCwZ2lmbAs8Mc66PI5g6Fv.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.14.11.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-14-11-62zeh8fXLnshEzLF4gWupTdmtiujtV.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-14-11-thumb-djxkKe1kuyoQqI8SjFouCKUQrP95GG.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.14.18.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-14-18-S5L4puvEsOx90G4eT7EqcexzIfzU3J.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-14-18-thumb-OJ4EbQExVFvnZ1tJyH1Nkmvm1gzZgh.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.14.25.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-14-25-00URkYNYL6b7FiYz43YmB5SdT9fU0F.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-14-25-thumb-c1Dgm2S1VaxU6MOVQideas1f4QdBw7.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.14.33.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-14-33-eJwE3vAjOae9q1by4BS48nw0KkgZKb.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-14-33-thumb-wa1HW90EFDY9nOGfOLIq3sMQYEZwk6.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.14.39.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-14-39-amNtgQAz8Wqy0TOySwGBMCxppoSgDf.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-14-39-thumb-pzfKTI4q8AclbmTupIKKOLhSbwpk03.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.14.45.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-14-45-wTmXmBWdbI8YlpO591rXBfqxOzRjHa.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-14-45-thumb-Vkq3jkYHFDWsPsp04MiC1XOihBXDDy.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.14.55.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-14-55-MUlEhXjaXxXva60WGjE6cFFKHvksXP.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-14-55-thumb-UkROjWkN5uh6IYpxyOEzRMGZA2ku8o.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.15.00.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-00-KwLPo4kPF2gAg3cbIIF57xGpRvGouY.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-00-thumb-7QoDhQkoDMiPaqgtAC2I8drGcNX9oC.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.15.14.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-14-Vubrozumrp0v1nXvqdu6MUjkYtJEb5.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-14-thumb-nf6zJPJh0ywjiOJWlpG9QFcWtoFLdz.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.15.21.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-21-KqbmKyOwGGtvPNSu2Kxfc7WvypVFQ5.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-21-thumb-MWUnw4WukdNG0J0aVGZRtjXQQwVPWY.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.15.26.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-26-82kAhGwn5yBh9H1vrz3HMGV7nVJQpk.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-26-thumb-fAnt2ndOxmXjq5X4xlWI8b1cqAKup2.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.15.33.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-33-0JNXbyE9ZEGpmlPb0nYC8UXqkESXK2.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-33-thumb-JXU7qbRNElyVcVUQIFICnBL1zNZPxw.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.15.37.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-37-y9wBXfVjiLcmX8xSjTxgbbMaq9n9jm.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-37-thumb-7UcBuEwwVvgI0rruO5Qrxk6DbJ6gU8.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.15.45.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-45-M7h0gv7zuZwygWGIKIN9ypwzSBkgRm.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-45-thumb-FfvvpM66r4jEsvqMJenalKuirONGcO.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.15.53.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-53-tF2iVBZtiv7dNURcKFBZ09qRe8Yirt.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-53-thumb-PzyTVDtVKixX17MsrhJE1Vf0vygz5O.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.15.57.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-57-PIm0JvXVTg7UytoDQ0vbfwGCFW8FmU.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-15-57-thumb-M2Hdtf9LZwhbetEyIuDwNx8OZJPBhO.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.16.04.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-04-oUuWBJDlvVzEkUye2pHKOtUpNnWzsn.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-04-thumb-ayyRHyr0uA3viD5NRxBN9JRVnkAOhL.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.16.12.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-12-DNplnALkT04GKpiFzrgiG8q7Vjfoi9.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-12-thumb-bc7LhgQhtD0T134fB4qY3UN9xRa1CB.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.16.19.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-19-oZok4i4aitY0m7vi3kcU8lQLJgkLLT.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-19-thumb-jDCDWpZIEYnzIAv6IhGy6LAiQed0QL.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.16.24.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-24-HPRZ9sO3hq5EERoVNABSDWTIwTEIC6.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-24-thumb-auNEmPcPTbqgrCw4UDsFTjGJmdvzjt.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.16.30.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-30-hxmfaFwRpyGU53wOvXkiptrIvcauJ5.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-30-thumb-cGlGM868OWNchaLmZe2vI5G19l61gr.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.16.38.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-38-9IQka1I2ujeU2HJb93HLEnIxM3KqTU.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-38-thumb-xbU2OYmgYE7bxYYTMadeoCfIyuyhb1.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.16.43.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-43-7zQYDaUV36mqkgEOYt86evSCuqqyGU.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-43-thumb-SL2IdNMXxnA7ub45HvsuRtJbkg29qX.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.16.47.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-47-bZaZzCsHd8yNbKqp80xF5p5ZZgGNN6.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-47-thumb-X5rvOOqRleDmI9wWYlSeyzJNabASq6.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.16.52.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-52-CBu4uFNOLumcsNm6ez7h05VZ8yIBnS.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-52-thumb-qVeRGW4rAqNIlvKmWHzh7L0TCDTyK7.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.16.57.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-57-yks4UGzIqB2PC2DtA0rRhVf148ADK7.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-16-57-thumb-hUOkio19W3ncaUzraIbb33RX2QzGqr.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.17.04.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-17-04-Rvokr4JGvCirm0fUWHDo3lkj0qq8iG.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-17-04-thumb-lOLAeGXtsLPYKvW5PiwsI5ZcksLgl6.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.17.14.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-17-14-0mN2dO0OqYHWEvkudb8b3Kyf3irGVG.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-17-14-thumb-tJoNjxhBSWGBK2eq5usV0YHdtz5U7V.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.17.21.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-17-21-MTeSUyXwQlJ8I9j5Lo4pmFdM3XqG9B.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-17-21-thumb-SWjpXdMk2L8VtqpS3QKStxgrkEKnkD.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.17.26.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-17-26-jHwYPeFh8H1h0zY8df1aN44EVmu4mQ.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-17-26-thumb-N0x0QDUZ7NaOjHgMenjshysuCadazq.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.17.30.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-17-30-QuwzJJsHayuyG0YQc5COjUD4uD4v4T.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-17-30-thumb-Kao1r0hnA9DLCQlPZK7p7OAzblFNQW.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.17.40.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-17-40-YGhf42S2qdVszFoD39gUJ3wNZ2EqPI.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-17-40-thumb-m9shBE2js5o58WZedsiYuxux7HGZBT.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.17.45.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-17-45-32ZJBAIa4kDDNM4IJpyevESuAqCXpW.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-17-45-thumb-WsnnIEXZW5h6waMMupPmmZOcShJNvZ.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.17.59.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-17-59-xzruegsMkJCro8z4nckcJ0Em15yg4m.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-17-59-thumb-th3oqWhcdVBpTRTRKbZs2pUtQxKzXm.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.18.07.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-18-07-pwA7yvnBjTA1jO0tRWMfg9w0SD7eky.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-18-07-thumb-3g2zBWF5DdLjAfAFA9x9P5e6MFolSD.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.18.15.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-18-15-dfjQCeNrIXHqR55TiP2UTErLj74tSN.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-18-15-thumb-LKAxZGP9eqSESb91BNsp5AyFAKaw1g.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.18.19.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-18-19-D57VAO9eqTfYPDNmogSUm7RUo69X7o.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-18-19-thumb-o9UStS4oGLzqzV8um9ZWxuqfcSThDO.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.18.24.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-18-24-20aFP9CDYEqeDdriW5X3tlQW1PJ5zP.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-18-24-thumb-3jciqiiGMeqVRBVpnRlWgJoCsdoi62.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.18.30.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-18-30-OOkqlTHPnaHvvpDG9J8ugrsansl3SJ.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-18-30-thumb-NqxT9Ps0jl6DF735ofaOHT66KB8whi.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.18.59.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-18-59-o1MQzcax0wAd8LbfUwpBbEKcWYdKef.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-18-59-thumb-Lunb5OB142KvIegVVkGimbAS6qUNm6.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.19.08.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-19-08-sNCMFBBB8qEAwOwctboo1rjwVaPz0c.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-19-08-thumb-OsBxqvBQ9r162p8xTXSRBfz9IuiiyB.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.19.15.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-19-15-YJjBsFfZLG46PRSGtnp8XUWNVUmqPa.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-19-15-thumb-unAjJyh241za4vAUUoTph3vtpmZjC8.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.19.31.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-19-31-gF93kEL2I2XFzw9VqoM7HxLAGco5nZ.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-19-31-thumb-PUhoMKeAvH4yZARhn3mtNQQECfFFqt.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.19.43.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-19-43-EhxQPwBV4BzUHp7onJRYLFLGcbfMf0.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-19-43-thumb-0KZg8sTKspIF31YVOwUzk54KFgC8C1.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.19.48.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-19-48-KNUJbayjC60TA7Nd06GPzXiwiSHmU8.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-19-48-thumb-jI2tMZKZqG8wPMsfdGcFr27seOz0Ll.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.20.06.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-20-06-CgvqEgcNEI2HdoRRjG0cI7HzsvM0QP.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-20-06-thumb-1AWcBmRnBuV9D6hwsWASnJLjg2DSzW.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.20.17.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-20-17-P8RVIpDjQ7Ml39VH6poTJDJsQdsl1M.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-20-17-thumb-Ir5LuJEboFTAhUK5KONMjNdPCJjNjt.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.20.35.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-20-35-HbVpi1heY9keqiHEN3Ntvu5gJ47eDK.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-20-35-thumb-rghtQ7FNdOyNYwI1vOvMMBEsIEYB4o.webp"
  },
  {
    "filename": "Screenshot 2026-02-10 at 23.20.41.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-20-41-AwSY7zEdAfwz8EqIr7NK7XgniAoJzS.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-10-at-23-20-41-thumb-navbkTzUtJeV4ZIwetB1as9ZYqtGL6.webp"
  },
  {
    "filename": "Screenshot 2026-02-15 at 13.28.37.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-15-at-13-28-37-Dz1qBpkEDMq9O6QjHsjlvoHs0BCQ6V.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-15-at-13-28-37-thumb-Lggub9zLQmAACrHRkZnEIjRzgoyCCN.webp"
  },
  {
    "filename": "Screenshot 2026-02-16 at 11.17.47.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-16-at-11-17-47-aldPT51SaQgvY914705T3uf8DmxbnK.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-16-at-11-17-47-thumb-VqrnV3DG6jnqp2PVIo07pXOUVPfDSW.webp"
  },
  {
    "filename": "Screenshot 2026-02-16 at 11.22.35.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-16-at-11-22-35-KrEbF9IQ09M9JoZK0GoLhRyEC0M4LH.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-16-at-11-22-35-thumb-blngM9eD80SN7udBcSGER3mEt6EjK1.webp"
  },
  {
    "filename": "Screenshot 2026-02-17 at 14.08.39.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-17-at-14-08-39-pg7a37db2P1nLR8xd6fTkmyIuSorSq.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-17-at-14-08-39-thumb-NZRNM08azPSNddxPvLn4NSKIy7wmUn.webp"
  },
  {
    "filename": "Screenshot 2026-02-17 at 14.09.31.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-17-at-14-09-31-4qupW38EyCidQbNSWkSiQqbT6Vtkk9.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-17-at-14-09-31-thumb-gzDWtARGzwi30ENzBkAyMSU81wwzqU.webp"
  },
  {
    "filename": "Screenshot 2026-02-18 at 16.36.10.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-18-at-16-36-10-rEyWGRag12NlybTDIwazzh8tkk6TB6.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-18-at-16-36-10-thumb-OCTzYOvzyTnKtCN4d5OlazCD9dkup9.webp"
  },
  {
    "filename": "Screenshot 2026-02-19 at 11.09.01.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-19-at-11-09-01-MkB2pg8flqehKV9eDklWYg2aAzO4pc.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-19-at-11-09-01-thumb-9nQCoEQ322PId2qNtO1rO8HAUAlsvW.webp"
  },
  {
    "filename": "Screenshot 2026-02-20 at 18.17.08.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-20-at-18-17-08-0ismzM48tjYBcKLMh3fQtYxQi29rsR.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-20-at-18-17-08-thumb-LFA3jQTLaxUZ5KmXKrg1XcqGzLoIdg.webp"
  },
  {
    "filename": "Screenshot 2026-02-20 at 19.33.24.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-20-at-19-33-24-TZ3FVUYQg8L7w4ofBuyLMdMqam3NPl.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-20-at-19-33-24-thumb-HyEFMiXxYhQGBhTFdOhGe4j0w9ssKr.webp"
  },
  {
    "filename": "Screenshot 2026-02-20 at 19.33.45.png",
    "url": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-20-at-19-33-45-QMwB60ucpCS6cSK5gXhz5OLRVKNL9T.webp",
    "thumbUrl": "https://lesiod2h05pfyhfb.public.blob.vercel-storage.com/valentine/poses/2026-02-20-at-19-33-45-thumb-Phl9Jdw5Ktb1FrrkeR6Adv9VtEhTC7.webp"
  }
] as const;

export const VALENTINE_POSES_BY_FILENAME: Readonly<Record<string, ValentinePoseEntry>> =
  Object.fromEntries(VALENTINE_POSES.map((p) => [p.filename, p]));
